### ISSUE TITLE
Awesome script!!! How to make 2 characters the initial search trigger?

### ISSUE THREAD

**Issue by inglesuniversal** [GianlucaChiarani/AutoFilter#1]
sometimes I need to start finding results from the second character on... Is that easy to fix or change?

**Comment by GianlucaChiarani** [comment]
Hi,
the filter by input starts with a minimum of 2 characters by default.

**Comment by inglesuniversal** [comment]
Thanks ... I will double check...

Is there a way to clear the input field and show all the contents back to normal on the screen using jQuery?

current settings...

$(function($) {
    $.autofilter({
      caseSensitive: false,
      duration: 500
    });
});

how can I reset it?

var clear = $('autofilter').val('');

would this work or is there a better approach.

Thanks big time!

**Comment by GianlucaChiarani** [comment]
Currently, there is no input reset function.
This is the best approach:
`$('[data-filter]').val('').keyup();`

**Comment by inglesuniversal** [comment]
Awesome... it worked like a charm!!!

Hope you can implement it on a future update.

onclick="resetSearch()"

**Comment by inglesuniversal** [comment]
Hello, on my website the filter is somehow starting from the 3rd character on...  Is there a way to make it start from the 1st character?

Thanks

**Comment by GianlucaChiarani** [comment]
Hi, i updated the plugin. I added a new option "minChars" to set the minimum characters.
