### ISSUE TITLE
<tr> not working

### ISSUE THREAD

**Issue by chrislarsenqlik** [GianlucaChiarani/AutoFilter#2]
Hi Gianluca, thanks a lot for this. I have a bootstrap table that has <tr> elements under a <tbody>.  I am trying to filter like: 
<tr data-tags="something, other"><td>Whatever</td></tr>

Is it expected for this to fail? 

Thanks in advance,
Chris

**Comment by GianlucaChiarani** [comment]
Hi Chris,
did you add the `data-tags` attribute in the other rows as well?

Gianluca

**Comment by chrislarsenqlik** [comment]
Found out the autofilter needs to run after the dom is completely loaded (at least the data-filter elements need to completely be there).. so i ran it inside a then **then()** after generating my tags.

**Comment by chrislarsenqlik** [comment]
Thanks for the quick attention!
