### ISSUE TITLE
Filter by Tag and Input combined?

### ISSUE THREAD

**Issue by andreasdirscherl** [GianlucaChiarani/AutoFilter#3]
HI, awesome work. Thank you!

Just a quick question: can I combine filter by tag and by input on content?
 I tried to do this using your codepen examples.  See here-> [https://codepen.io/andreasdirscherl/pen/NWwqPVy](https://codepen.io/andreasdirscherl/pen/NWwqPVy)
But it only works partially: if I input "cat"  or "dog" it works, all other text inputs do not.
So I'm wondering if it could work somehow?

Thank you!

**Comment by GianlucaChiarani** [comment]
Hi Andreas,
the examples were out of date. I have already fixed the bug with version 0.3 (https://cdn.jsdelivr.net/gh/GianlucaChiarani/AutoFilter@0.3/autofilter.js).

Thank you,
Gianluca

**Comment by andreasdirscherl** [comment]
Thank you for your quick response and fixing the code! Great. It now does find 'monkeys', too :-)

Am I right in assuming that when I combine the data-tag and data-to-filter then the text input is limited to the keywords specified in data-tags? Because that's what's happening now for me. When data-to-filter is used alone, it finds all the text between the html tags.
So keeping with the example: When I input "some" or "pretty" nothing is found.
Just wanted to make sure I follow your logic... Thank you!

**Comment by GianlucaChiarani** [comment]
Exactly: data-tags has priority over data-to-filter. Html content and data-tags' value are not merged together.

**Comment by andreasdirscherl** [comment]
OK, good to know. Thanks!

**Comment by andreasdirscherl** [comment]
Sorry to bother you again, but I would one more question.
Based on your response, I played around a little more and found an interesting "feature" in your bug. Basically, with V0.2 I can achieve 100% what I was looking for, namely using the buttons and the input fields simultaneously. With the fixed V0.3 it doesn't work anymore. 

But since I am taking advantage of that "bug" I wanted to ask you if you see any unwanted side effects or problems with me using it?

This is the html, and you can see it "in action" on [my codepen](https://codepen.io/andreasdirscherl/pen/NWwqPVy)
```
<div>
  <span data-filter>All</span>
  <span data-filter="cat">Cats</span>  
  <span data-filter="pretty">Pretty</span>
  <span data-filter="dog">Dogs</span>
  <span data-filter="monkey">Monkeys</span>
</div>

<div>
  <input type="text" placeholder="Search..." data-filter />
</div>

<div>
  <div data-to-filter>Some pretty cats and dogs!</div>
  <div data-to-filter>Some pretty Dogs</div>
  <div data-to-filter>Cats and Monkeys!</div>
  <div data-to-filter>Only Monkeys!</div>
</div>
```

**Comment by GianlucaChiarani** [comment]
To get the same result in v. 0.3, it is necessary to set `subString: true`

**Comment by andreasdirscherl** [comment]
Of course, duh!
Fantastic - works like a charm now and is EXACTLY what I was looking for.
THANK YOU! 🙏
