### ISSUE TITLE
Possibility to pre-filter by URL parameter?

### ISSUE THREAD

**Issue by instantflorian** [GianlucaChiarani/AutoFilter#4]
Hi,
great script, works like a charm. Thank you very much.

Is it possible to pre-filter a list by URL parameter, e.g. ```mypage.php?filter=foo```, so that only entries with "foo" tag or content are visible?

**Comment by GianlucaChiarani** [comment]
Hi, 
currently it is not possible to pre-filter but this could be a new feature in future.

To work around you could check the `document.location.href` variable and trigger the click of the filter button: `$('[data-filter="cat"]').click()`

**Comment by instantflorian** [comment]
Thank you for your lightning fast reply.
I did not get it working yet, have to play around with this some more time.
This is my code 
```
const queryString = window.location.search;
const urlParams = new URLSearchParams(queryString);
const searchParam = urlParams.get('search');

if (searchParam!=null) {  	
      $('[data-filter="'+searchParam+'"]').click()
}
```
(it does not work when hardcoding an existing parameter either)

**Comment by GianlucaChiarani** [comment]
Did you initialize the plugin first?

`$.autofilter();`

**Comment by instantflorian** [comment]
Yes. But to make it harder ;-), I'm trying to combine tags and input like in issue #3 .
So above the contents to filter I have
```
<ul>
  <li data-filter="">All</li>
  <li data-filter="Dogs">Dogs</li>
  <li data-filter="Cats">Cats</li>
    ...
</ul>
<input type="text"  data-filter />
```

And the script part looks like this:
```
<script>
$(function($) {
    $.autofilter({
subString: true,
animation: true,
duration: 300
  });
});
</script>
<script>
const queryString = window.location.search;
const urlParams = new URLSearchParams(queryString);
const searchParam = urlParams.get('search');

if (searchParam!=null) {  	
      $('[data-filter="'+searchParam+'"]').click()
}
</script>
```

**Comment by GianlucaChiarani** [comment]
Hi,
sorry for the late response. If it can still be useful to you, in v0.4 I added the urlSearchParam option, which allows filtering based on a parameter in the URL.
